### ISSUE TITLE
composer 无法安装库

### ISSUE THREAD

**Issue by Witype** [aliyun/openapi-sdk-php-client#114]
* **PHP Version**:7.0
* **Platform**:PHP
* **Product**:SMS
* **Product Version**:1.0.26
* **API**:SMS

![image](https://user-images.githubusercontent.com/6899329/55157814-54237700-5198-11e9-8424-8a80fc2c6fed.png)
[Composer\Downloader\TransportException]                                                                                                                                               
  The "https://packagist.phpcomposer.com/p/provider-2018%24abcc0e6639791f327782ff6eed4bdcb690728c98e12e818f3964beb16ec0416f.json" file could not be downloaded (HTTP/1.1 404 Not Found) 

要么就是一直卡在这，
![image](https://user-images.githubusercontent.com/6899329/55157887-87fe9c80-5198-11e9-8fcb-c612d7f40e90.png)

**Comment by songshenzong** [comment]
> * **PHP Version**:7.0
> * **Platform**:PHP
> * **Product**:SMS
> * **Product Version**:1.0.26
> * **API**:SMS
> 
> ![image](https://user-images.githubusercontent.com/6899329/55157814-54237700-5198-11e9-8424-8a80fc2c6fed.png)
> [Composer\Downloader\TransportException]
> The "https://packagist.phpcomposer.com/p/provider-2018%24abcc0e6639791f327782ff6eed4bdcb690728c98e12e818f3964beb16ec0416f.json" file could not be downloaded (HTTP/1.1 404 Not Found)

您好，这是您本地网络的问题，建议您寻找一个composer加速器，修改仓库的镜像地址。

**Comment by Yooole** [comment]
遇到一样的问题 只能用zip包

**Comment by songshenzong** [comment]
> 遇到一样的问题 只能用zip包

您好，这是您本地网络的问题，建议您寻找一个composer加速器，修改仓库的镜像地址。
