### ISSUE TITLE
能提供精简版么

### ISSUE THREAD

**Issue by anrip** [aliyun/openapi-sdk-php-client#141]
我就是要集成个短信接口，整个项目不超过100个文件，咱们的sdk弄下来就 600多个文件。真是有些难以接受

**Comment by songshenzong** [comment]
> 我就是要集成个短信接口，整个项目不超过100个文件，咱们的sdk弄下来就 600多个文件。真是有些难以接受

您好，如果您希望使用体积小的工具包，请使用本仓库的 Alibaba Cloud Client for PHP 发起请求，本工具包共91个有效代码文件，Alibaba Cloud SDK for PHP 是基于 Client 提供了产品快捷访问方法的工具包集合，目前共有719个有效代码文件。

**Comment by songshenzong** [comment]
> 我就是要集成个短信接口，整个项目不超过100个文件，咱们的sdk弄下来就 600多个文件。真是有些难以接受

依赖包是基于支持 Composer 开发的，安装相关依赖，vendor 目录不可避免会产品许多文件，这个符合PHP社区情况。

**Comment by songshenzong** [comment]
> 我就是要集成个短信接口，整个项目不超过100个文件，咱们的sdk弄下来就 600多个文件。真是有些难以接受

我们推荐使用 Composer 方式进行安装，这也是大部分客户的需求，使用 Composer 不可避免会生成依赖文件到 vendor 目录。如果您在乎项目的性能，可以启动优化选项、使用 OPCache 等。

**Comment by songshenzong** [comment]
> 我就是要集成个短信接口，整个项目不超过100个文件，咱们的sdk弄下来就 600多个文件。真是有些难以接受

如果没有其他疑问，我们将关闭此Issue。
