### ISSUE TITLE
我想请问下这个包是阿里云的集齐翻译的吗，为何一点都看不懂

### ISSUE THREAD

**Issue by Yooole** [aliyun/openapi-sdk-php-client#172]
我想请问下这个包是阿里云的集齐翻译的吗，为何一点都看不懂

**Comment by songshenzong** [comment]
> 我想请问下这个包是阿里云的集齐翻译的吗，为何一点都看不懂

请问是什么看不懂？

**Comment by AxiosCros** [comment]
是 “集齐”=“机器” 吗

当前 client 仓库是 SDK 核心，不是机器翻译的。

各个产品的 SDK 是由生成器根据产品接口定义而生成的。

**Comment by songshenzong** [comment]
> 我想请问下这个包是阿里云的集齐翻译的吗，为何一点都看不懂

如果没有其它问题，此issue将被关闭。
