### ISSUE TITLE
说明文档写的太装逼，根本不能看

### ISSUE THREAD

**Issue by huangdengpan** [aliyun/openapi-sdk-php-client#207]
文档逼格太高，你们这个API是写出来只在大神圈里交流么。产品好是好，就是根据你们这个文档没法用啊。白瞎了阿里的产品。

**Comment by huangdengpan** [comment]
ROA是什么RPC是什么？

**Comment by songshenzong** [comment]
> 文档逼格太高，你们这个API是写出来只在大神圈里交流么。产品好是好，就是根据你们这个文档没法用啊。白瞎了阿里的产品。

请问哪里有疑问？

**Comment by songshenzong** [comment]
> ROA是什么RPC是什么？

请参考具体产品的产品文档，不同产品风格不同。

**Comment by JacksonTian** [comment]
@huangdengpan  这个仓库是阿里云 PHP SDK 的核心依赖部分，正常使用，推荐的是 https://github.com/aliyun/openapi-sdk-php#quick-examples 的方式。

直接用产品的 SDK 是不用关心内部的细节是怎样的。核心部分仅用来支持一些未生成 SDK 的 OpenAPI 的调用。
