### ISSUE TITLE
SDK依赖了guzzlehttp/guzzle，出现idn_to_ascii() INTL_IDNA_VARIANT_2003

### ISSUE THREAD

**Issue by crazyfd** [aliyun/openapi-sdk-php-client#210]
php 7.4
SDK依赖了guzzlehttp/guzzle": "^6.3" ,在高版本上会出现idn_to_ascii() INTL_IDNA_VARIANT_2003

而guzzlehttp/guzzle 6.3的版本再php7.3+环境有bug，参考，
idn_to_ascii() fix for old PHP versions    https://github.com/guzzle/guzzle/pull/2489
导致官方包不能用，建议修复。

**Comment by songshenzong** [comment]
PHP7.4不会安装6.3，经过多版本集成测试，尚未发现此问题。

**Comment by songshenzong** [comment]
> php 7.4
> SDK依赖了guzzlehttp/guzzle": "^6.3" ,在高版本上会出现idn_to_ascii() INTL_IDNA_VARIANT_2003
> 
> 而guzzlehttp/guzzle 6.3的版本再php7.3+环境有bug，参考，
> idn_to_ascii() fix for old PHP versions [guzzle/guzzle#2489](https://github.com/guzzle/guzzle/pull/2489)
> 导致官方包不能用，建议修复。

如果没有问题，此issue将被关闭。
