### ISSUE TITLE
带空字符串参数的请求会出现签名错误

### ISSUE THREAD

**Issue by ghostoy** [aliyun/openapi-sdk-php-client#224]
* **PHP 版本**：7.1-7.4
* **平台**：Linux
* **产品名称**：Vod视频直播
* **产品版本**：1.4.25+
* **API**：任何API

```php
$query = [
  'Title' => 'Title',
  'Description' => '', // 只要是空的就会报签名错误
  'FileName' => 'test.mp4',
];
$request = Vod::v20170321()->createUploadVideo([
  'query' => $query,
])->endpoint($endpoint)
  ->request();
```

这个问题从1.5.25开始出现

**Comment by songshenzong** [comment]
> * **PHP 版本**：7.1-7.4
> * **平台**：Linux
> * **产品名称**：Vod视频直播
> * **产品版本**：1.4.25+
> * **API**：任何API
> 
> ```
> $query = [
>   'Title' => 'Title',
>   'Description' => '', // 只要是空的就会报签名错误
>   'FileName' => 'test.mp4',
> ];
> $request = Vod::v20170321()->createUploadVideo([
>   'query' => $query,
> ])->endpoint($endpoint)
>   ->request();
> ```
> 
> 这个问题从1.5.25开始出现

已收到，请稍后。

**Comment by ghostoy** [comment]
升级到1.4.29后问题修复
