### ISSUE TITLE
不想使用 AlibabaCloud 助手类

### ISSUE THREAD

**Issue by kaysonwu** [aliyun/openapi-sdk-php-client#229]
**您的功能请求是否与问题有关？ 请描述一下。**
否

**描述你想要的解决方案**

能否直接把 `Client` 对象传递给 `Request` 啊？非要整个 `name`， 非要用 `AlibabaCloud ` 助手，感觉一点不香，语义也不是很清楚

**描述您考虑过的替代方案**
继承 `Request` 类，覆盖父类方法

**Comment by songshenzong** [comment]
> **您的功能请求是否与问题有关？ 请描述一下。**
> 否
> 
> **描述你想要的解决方案**
> 
> 能否直接把 `Client` 对象传递给 `Request` 啊？非要整个 `name`， 非要用 `AlibabaCloud ` 助手，感觉一点不香，语义也不是很清楚
> 
> **描述您考虑过的替代方案**
> 继承 `Request` 类，覆盖父类方法

您好，暂不支持，这样的设计是为了统一用法，兼容SDK\CLI，兼容多项目的不同客户端凭据配置。
