### ISSUE TITLE
InvalidAction.NotFound: Specified api is not found

### ISSUE THREAD

**Issue by wangyabener** [aliyun/openapi-sdk-php-client#230]
框架：Laravel6.x
PHP版本：7.3.11
SDK：图像搜索 ImageSearch
```
AlibabaCloud::accessKeyClient(env('ALI_IMAGE_KEY'), env('ALI_IMAGE_SECRET'))
    ->regionId('cn-shanghai')
    ->asDefaultClient();

$request = AlibabaCloud::roa()
    ->product('ImageSearch')
    ->method('POST')
    ->version('2019-03-25')
    ->action('SearchImage')
    ->options([
        'query' => [
            'PicContent' => 'test'
        ]
    ])
    ->timeout(10)
    ->request();
```

InvalidAction.NotFound: Specified api is not found, please check your url and method. RequestId: 5B2C3075-5D8C-410C-8077-B87DE19E2FAB POST \"http://imagesearch.cn-shanghai.aliyuncs.com/?Date=2020-3-15&PicContent=test&Version=2019-03-25\" 404

**Comment by wangyabener** [comment]
如果手动在链式调用里加上
->pathPattern('/v2/image/search')
就可以了

有点搞不清楚sdk包
https://github.com/alibabacloud-sdk-php/imagesearch
这个类 ImageSearchApiResolver
/** @var string */
public $pathPattern = '/v2/image/add';
这个属性的作用是什么

**Comment by songshenzong** [comment]
> 如果手动在链式调用里加上
> ->pathPattern('/v2/image/search')
> 就可以了
> 
> 有点搞不清楚sdk包
> https://github.com/alibabacloud-sdk-php/imagesearch
> 这个类 ImageSearchApiResolver
> /** @var string */
> public $pathPattern = '/v2/image/add';
> 这个属性的作用是什么

这个属性是定义默认的请求路径

**Comment by songshenzong** [comment]
> 框架：Laravel6.x
> PHP版本：7.3.11
> SDK：图像搜索 ImageSearch
> 
> ```
> AlibabaCloud::accessKeyClient(env('ALI_IMAGE_KEY'), env('ALI_IMAGE_SECRET'))
>     ->regionId('cn-shanghai')
>     ->asDefaultClient();
> 
> $request = AlibabaCloud::roa()
>     ->product('ImageSearch')
>     ->method('POST')
>     ->version('2019-03-25')
>     ->action('SearchImage')
>     ->options([
>         'query' => [
>             'PicContent' => 'test'
>         ]
>     ])
>     ->timeout(10)
>     ->request();
> ```
> 
> InvalidAction.NotFound: Specified api is not found, please check your url and method. RequestId: 5B2C3075-5D8C-410C-8077-B87DE19E2FAB POST "[http://imagesearch.cn-shanghai.aliyuncs.com/?Date=2020-3-15&PicContent=test&Version=2019-03-25\](http://imagesearch.cn-shanghai.aliyuncs.com/?Date=2020-3-15&PicContent=test&Version=2019-03-25%5C)" 404

如果没有其他问题，这个Issue将被关闭
