### ISSUE TITLE
扩展包支持范围是大于5.6就行，但是alibabacloud依赖包guzzlehttp确要求7以上，所以5.6的版本安装这个依赖报错

### ISSUE THREAD

**Issue by bafeiyu** [aliyun/openapi-sdk-php-client#232]
* **PHP 版本**：5.6
* **平台**：linux
* **产品名称**：短信服务
* **产品版本**：dev-master
* **API**：SendMessageToGlobe

`
syntax error, unexpected ':', expecting '{'
/vendor/guzzlehttp/guzzle/src/functions.php 　LINE: 16
`

**Comment by songshenzong** [comment]
> * **PHP 版本**：5.6
> * **平台**：linux
> * **产品名称**：短信服务
> * **产品版本**：dev-master
> * **API**：SendMessageToGlobe
> 
> `syntax error, unexpected ':', expecting '{' /vendor/guzzlehttp/guzzle/src/functions.php 　LINE: 16`

您好，约束是^6.3|^7.0，请回复本地的版本和composer客户端版本。

**Comment by AxiosCros** [comment]
依赖包是不是拷贝过去的？如果是通过 composer 安装，composer 会基于当前 PHP 环境，选择兼容的 guzzlehttp 6.* 版本的。

**Comment by bafeiyu** [comment]
> 依赖包是不是拷贝过去的？如果是通过 composer 安装，composer 会基于当前 PHP 环境，选择兼容的 guzzlehttp 6.* 版本的。

感谢，知道是什么原因了。我本地安装php是7.3版本的

**Comment by bafeiyu** [comment]
![微信图片_20201015152849](https://user-images.githubusercontent.com/8556733/96090671-2711f300-0efb-11eb-9017-857651da433f.png)

使用5.6版本的已经安装不上了

**Comment by AxiosCros** [comment]
删除 composer.lock 文件后，再安装试试
