### ISSUE TITLE
Class 'GuzzleHttp\Psr7\Uri' not found

### ISSUE THREAD

**Issue by hyyyp** [aliyun/openapi-sdk-php-client#241]
查遍整个项目 都没发现Uri定义的地方

**Comment by AxiosCros** [comment]
GuzzleHttp\Psr7\Uri 是在 [`guzzlehttp/psr7`](https://github.com/guzzle/psr7/blob/master/src/Uri.php) 这个 composer 组建里的。检查下 guzzlehttp/guzzl 这个组建是否安装好。

**Comment by hyyyp** [comment]
并不是所有开发者都使用composer 现在阿里云的SDK都集合在一起了  这个真的合适吗

**Comment by hyyyp** [comment]
开发者经常帮很多中小企 对接一些阿里云产品  但是他们的程序 并不是非常规范  想快速开发产品 不想导入这种集合SDK

**Comment by AxiosCros** [comment]
感谢建议，目前开发资源有限，以后可能会考虑增加源码交付的方式。
如果当前问题已解决，可以关闭这个 issue。

**Comment by AxiosCros** [comment]
如没有其他问题，我先关闭这个 issue。如还有问题，可以 reopen。
