### ISSUE TITLE
\GuzzleHttp\Psr7\stream_for 函数即将废弃，建议用 Utils::streamFor 替代

### ISSUE THREAD

**Issue by jobsssss** [aliyun/openapi-sdk-php-client#249]
alibabacloud/tea/src/Request.php 文件的第92行采用了 \GuzzleHttp\Psr7\stream_for 函数，该函数已不建议使用，会在接下来一个版本中废弃，建议使用 Utils::streamFor 替换：

![image](https://user-images.githubusercontent.com/9812992/117762393-a716f600-b25b-11eb-8814-9a13c2b1e72b.png)

**Comment by AxiosCros** [comment]
https://github.com/aliyun/tea-php/pull/44

已修复
