### ISSUE TITLE
错误消息Call to undefined function GuzzleHttp\Psr7\parse_query()

### ISSUE THREAD

**Issue by qqingdou** [aliyun/openapi-sdk-php-client#250]
GuzzleHttp依赖下不存在这个这个函数，只有Query::parse
改成GuzzleHttp\Psr7\Query::parse() 是OK的

* **PHP Version**:7.1
* **Platform**:Linux
* **Product**:
* **Product Version**:
* **API**:

**Comment by AxiosCros** [comment]
https://github.com/guzzle/psr7#upgrading-from-function-api

```guzzle/psr7``` 2.0 之前版本时有的，请先降级使用 guzzle/psr7。
感谢反馈，稍后我去修复下这个问题。
