### ISSUE TITLE
open_basedir 报错

### ISSUE THREAD

**Issue by pangongzi** [aliyun/openapi-sdk-php-client#57]
is_file(): open_basedir restriction in effect. File(/home/www/.alibabacloud/credentials) is not within the allowed path(s)

**Comment by JacksonTian** [comment]
@songshenzong 把 credentials 的容错性做好一点。

**Comment by songshenzong** [comment]
> is not within the allowed path(s)

It seems you need to add directory you use form tempnam into open_basedir or ask your server adminsitrator to turn it off reference: https://secure.php.net/manual/en/ini.core.php#ini.open-basedir

At the same time, we will update the code to solve this problem, and we will reply to you after solving this problem.

**Comment by songshenzong** [comment]
> is_file(): open_basedir restriction in effect. File(/home/www/.alibabacloud/credentials) is not within the allowed path(s)

Hello, we have released V1.0.12 to support `open_basedir`. Please run composer update to update your dependencies.

**Comment by pangongzi** [comment]
think you
